services:
  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 45s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: schedule
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5430:5432
    networks:
      - local-development

  app:
    links:
      - postgres
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    env_file:
      - ./src/config/settings/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - local-development

volumes:
  pgdata:

networks:
  local-development:
